# Welcome to Jekyll!
#

# Site settings
title: A BETTER WORLD
description: |
  你来人间一趟，你要看看太阳， 和你的心上人，一起走在街上。 
owner: Zachary Zhang # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: 825812377@qq.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zacharypt.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/zacharypt
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    

markdown: kramdown
mathjax: disabled
sass:
  style: compressed
#sass:
#  style: compressed
