# Welcome to Jekyll!
#

# Site settings
title: A BETTER WORLD
description: |
  你来人间一趟，你要看看太阳， 和你的心上人，一起走在街上。 
owner: Zachary Zhang # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: 825812377@qq.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zacharypt.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/zacharypt
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:  
  #reddit:
  #stubleupon:
  #delicious: 
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
    #amazon:

# Build settings
 
 permalink: /:year/:month/:day/:title.html
 markdown: kramdown
 highlighter: rouge
 
  mathjax: disabled
  sass:
     style: compressed
 #sass:		
 #  style: compressed
